export const ORDER_INPUT_REQUEST = "ORDER_INPUT_REQUEST"
export const ORDER_INPUT_SUCCESS = "ORDER_INPUT_SUCCESS"
export const ORDER_INPUT_FAIL = "ORDER_INPUT_FAIL" 

export const ORDER_FINDONE_REQUEST = "ORDER_FINDONE_REQUEST"
export const ORDER_FINDONE_SUCCESS = "ORDER_FINDONE_SUCCESS"
export const ORDER_FINDONE_FAIL = "ORDER_FINDONE_FAIL"

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST"
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS"
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL"

export const ORDER_FINDALL_REQUEST = "ORDER_FINDALL_REQUEST"
export const ORDER_FINDALL_SUCCESS = "ORDER_FINDALL_SUCCESS"
export const ORDER_FINDALL_FAIL = "ORDER_FINDALL_FAIL"