export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCES";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_FINDONE_REQUEST = "USER_FINDONE_REQUEST";
export const USER_FINDONE_SUCCESS = "USER_FINDONE_SUCCESS";
export const USER_FINDONE_FAIL = "USER_FINDONE_FAIL";